// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kernel_rbf_cpp
NumericMatrix kernel_rbf_cpp(const NumericMatrix& X1, const NumericMatrix& X2, double sigma);
RcppExport SEXP _psvr_kernel_rbf_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_rbf_cpp(X1, X2, sigma));
    return rcpp_result_gen;
END_RCPP
}
// kernel_linear_cpp
NumericMatrix kernel_linear_cpp(const NumericMatrix& X1, const NumericMatrix& X2);
RcppExport SEXP _psvr_kernel_linear_cpp(SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_linear_cpp(X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// kernel_poly_cpp
NumericMatrix kernel_poly_cpp(const NumericMatrix& X1, const NumericMatrix& X2, double coef0, int degree);
RcppExport SEXP _psvr_kernel_poly_cpp(SEXP X1SEXP, SEXP X2SEXP, SEXP coef0SEXP, SEXP degreeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< double >::type coef0(coef0SEXP);
    Rcpp::traits::input_parameter< int >::type degree(degreeSEXP);
    rcpp_result_gen = Rcpp::wrap(kernel_poly_cpp(X1, X2, coef0, degree));
    return rcpp_result_gen;
END_RCPP
}
// psvr_smo_fit_rcpp
List psvr_smo_fit_rcpp(const NumericMatrix& Omega, const NumericVector& y, const List& opts);
RcppExport SEXP _psvr_psvr_smo_fit_rcpp(SEXP OmegaSEXP, SEXP ySEXP, SEXP optsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const List& >::type opts(optsSEXP);
    rcpp_result_gen = Rcpp::wrap(psvr_smo_fit_rcpp(Omega, y, opts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_psvr_kernel_rbf_cpp", (DL_FUNC) &_psvr_kernel_rbf_cpp, 3},
    {"_psvr_kernel_linear_cpp", (DL_FUNC) &_psvr_kernel_linear_cpp, 2},
    {"_psvr_kernel_poly_cpp", (DL_FUNC) &_psvr_kernel_poly_cpp, 4},
    {"_psvr_psvr_smo_fit_rcpp", (DL_FUNC) &_psvr_psvr_smo_fit_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_psvr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
