# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel_linear_cpp <- function(X1, X2) {
    .Call(`_psvr_kernel_linear_cpp`, X1, X2)
}

kernel_poly_cpp <- function(X1, X2, coef0, degree) {
    .Call(`_psvr_kernel_poly_cpp`, X1, X2, coef0, degree)
}

kernel_rbf_cpp <- function(X1, X2, sigma) {
    .Call(`_psvr_kernel_rbf_cpp`, X1, X2, sigma)
}

